# Index cardiotoxicity {#index_c}

> Index cardiotoxicity identifier is [ic]

There is a little ambiguity here: index cardiotoxicity refers both to the date of cardiotoxicity diagnosis AND date of hospital admission (if any) for this cardiotoxicity.

## Abbreviations

+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Abbreviation(s)                                  | Feature                                                                                                                                                                                                                                                                                                         |
+==================================================+=================================================================================================================================================================================================================================================================================================================+
| Clinical work-up                                 |                                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `sy`                                             | Symptoms                                                                                                                                                                                                                                                                                                        |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ctx`                                            | Cardiotoxicity (used for the description of timings between a ctx symptoms `ctx sy` and index date, and grading).                                                                                                                                                                                               |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `pe`                                             | Physical examination features                                                                                                                                                                                                                                                                                   |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `irae`                                           | Features of non-cardiac immune related adverse events at the index date                                                                                                                                                                                                                                         |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `hyper, hypo, aiha, attp, hus, aa, id, bd, scar` | For iraes subclasses, small adds to refer to the correct subclass (hyperthyroidism, hypothyroidism, auto-immune hemolytic anemia, acquired thrombotic thrombocytopenic purpura, hemolytic and uremic syndrome, aplastic anemia, inflammatory dermatitis, bullous dermatosis, severe cutaneous adverse reaction) |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Exams                                            |                                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `bx`                                             | Biopsy features (muscular, cardiac, other)                                                                                                                                                                                                                                                                      |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `lhc`                                            | Left Heart Catheterization                                                                                                                                                                                                                                                                                      |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Treatment section                                |                                                                                                                                                                                                                                                                                                                 |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `tx`                                             |                                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| immsup                                           | Immunosuppressant                                                                                                                                                                                                                                                                                               |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                  | 4-character abbreviation for immunosuppressants                                                                                                                                                                                                                                                                 |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ivig`                                           | Intravenous Immunoglobulin                                                                                                                                                                                                                                                                                      |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `plas`                                           | Plasmapheresis (PLEX)                                                                                                                                                                                                                                                                                           |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `tacy`                                           | Tacrolimus or cyclosporin                                                                                                                                                                                                                                                                                       |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `myco`                                           | Mycophenolate mofetil                                                                                                                                                                                                                                                                                           |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `othr`                                           | Other immunosuppressant                                                                                                                                                                                                                                                                                         |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `athg`                                           | ATG / thymoglobulin                                                                                                                                                                                                                                                                                             |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `infl`                                           | Infliximab or other anti-TNFalpha                                                                                                                                                                                                                                                                               |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `abab`                                           | Abatacept or belatacept                                                                                                                                                                                                                                                                                         |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `mtor`                                           | mTOR inhibitors (temsirolimus, everolimus, sirolimus)                                                                                                                                                                                                                                                           |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `cycl`                                           | Cyclophosphamide                                                                                                                                                                                                                                                                                                |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `azat`                                           | Azathioprine                                                                                                                                                                                                                                                                                                    |
|                                                  |                                                                                                                                                                                                                                                                                                                 |
| `ritu`                                           | Rituximab                                                                                                                                                                                                                                                                                                       |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `ms`                                             | Mechanical support                                                                                                                                                                                                                                                                                              |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| `aa`                                             | Anti-arrhythmic drugs or devices                                                                                                                                                                                                                                                                                |
+--------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Biological features

Most normal values of biological parameters are different from one lab to another. Also, users may report bio vars according to different scales.

Examples: troponin upper limit of normal may range from \~ 0.01 to \~ 50. Complete blood count can be reported in G/L or 10\^-3/µL (even if the var field asked for reporting with one of them).

It is advised to express biological parameters according to their normal value range if known, or to contrast them into ratios that get rid of the unit (example: neutrophil to lymphocyte ratio)

## Diagnosis staging according to Bonaca's

Bonaca's criteria were summarised in `ic_ctx1_certainty_adjudication`.
