# Electrocardiograms {#ekg}

**There are two identifiers for baseline and index electrocardiograms**

> Baseline electrocardiogram identifiers are [be] and [be2]
>
> Index electrocardiogram identifiers are [ie] and [ie2]

Although there are 2 identifiers for each, they refer to the same EKG (e.g. `ie` and `ie2` are the same EKG).

The duplicates were created to have a standard interpretation of EKGs in addition to the interpretation provided by the reporter.

Benay Ozbay reviewed all uploaded EKG files up to November 2022, and reported data into `be2` and `ie2`. This means that `be2` and `ie2` features should be preferred over `be` and `ie` ones, when both are available.

Subsequent EKG during follow-up are in the index hospitalization instrument `ih_ekg` or in the follow-up instrument `fu_ekg`. (no expert review)

## Analysis

All these four EKGs (be, ie, ih, fu) have an `analysis` feature. Below is the correspondence of each checkbox number.

Analysis feature exists for both be/be2 and ie/ie2.

+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| analysis_num | Feature                                                                                                                                                                             |
+==============+=====================================================================================================================================================================================+
| 1            | Normal Sinus Rhythm                                                                                                                                                                 |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2            | Accelerated Idioventricular Rhythm                                                                                                                                                  |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3            | Accelerated Junctional Rhythm                                                                                                                                                       |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4            | Asystole                                                                                                                                                                            |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5            | Atrial Fibrillation                                                                                                                                                                 |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6            | Atrial Flutter                                                                                                                                                                      |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 30           | AV Nodal Reentrant Tachycardia                                                                                                                                                      |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7            | Bundle Branch Block, Nonspecific                                                                                                                                                    |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 46           | Bundle Branch Block, Left Bundle (defined as QRS ≥120ms + broad notched or slurred R wave in I, aVL, V5 & V6)                                                                       |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 48           | Bundle Branch Block, Right Bundle (defined as QRS ≥120ms; RSR' pattern in V1-V3; and slurred S wave in I, aVL, V5-6)                                                                |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9            | Escape Rhythm, Ventricular                                                                                                                                                          |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10           | Escape Rhythm, Junctional                                                                                                                                                           |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 47           | Fasicular Block, Left Anterior                                                                                                                                                      |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 49           | Fasicular Block, Left Posterior                                                                                                                                                     |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8            | Heart Block, First Degree                                                                                                                                                           |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 24           | Heart Block, Second Degree Type II                                                                                                                                                  |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 31           | Heart Block, Third Degree                                                                                                                                                           |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11           | Junctional Tachycardia                                                                                                                                                              |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 52           | Left Ventricular Hypertrophy (defined as sum of S wave in V1 + R wave in V5 or V6 ≥35 mm or R wave in aVL ≥11 mm)                                                                   |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 53           | Low QRS Voltage (defined as QRS voltage \< 5 mm in the limb leads and/or \< 10mm in precordial leads.)                                                                              |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12           | Multifocal Atrial Tachycardia                                                                                                                                                       |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 54           | PR-segment Depression (defined as ≥0.5 mm PR depression from TP segment)                                                                                                            |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 56           | P wave abnormality suggesting left atrial enlargement                                                                                                                               |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 57           | P wave abnormality suggesting right atrial enlargement                                                                                                                              |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 17           | Premature Atrial Complex                                                                                                                                                            |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20           | Premature Ventricular Complex Bigeminy                                                                                                                                              |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 21           | Premature Ventricular Complex Quadrigeminy                                                                                                                                          |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 22           | Premature Ventricular Complex Trigeminy                                                                                                                                             |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 39           | Pulseless Electrical Activity                                                                                                                                                       |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 51           | Q Waves, Pathological                                                                                                                                                               |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 26           | Sinus Arrest / Sinus Pause                                                                                                                                                          |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 27           | Sinus Arrhythmia                                                                                                                                                                    |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 28           | Sinus Bradycardia                                                                                                                                                                   |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 58           | Sinus Dysfunction                                                                                                                                                                   |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 29           | Sinus Tachycardia                                                                                                                                                                   |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 40           | ST segment elevation, diffuse (defined as ≥1 mm unless in leads V2 to V3 where defined as ≥2 mm in men ≥40 years, ≥2.5 mm in men \< 40 years, and ≥1.5 mm in women)                 |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 41           | ST segment elevation, regional (defined as ≥1 mm unless in leads V2 to V3 where defined as ≥2 mm in men ≥40 years, ≥2.5 mm in men \< 40 years, and ≥1.5 mm in women)                |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 42           | ST segment depression, diffuse (defined as ≥0.5 mm below the baseline)                                                                                                              |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 45           | Tall T waves (defined as \>10 mm in precordial leads or \>5 mm in the limb leads)                                                                                                   |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 44           | T wave inversions                                                                                                                                                                   |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 55           | T wave notching in ≥ 3 leads (defined as bifid T-wave with a notch duration between the 2 peaks ≥40 ms and an amplitude ≥0.5 mm)                                                    |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 32           | Ventricular Fibrillation                                                                                                                                                            |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 50           | Ventricular Tachycardia, Non-sustained (defined as 3 or more premature ventricular contractions for \< 30 seconds at a rate of \>100 beats per minute without hemodynamic collapse) |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 33           | Ventricular Tachycardia Unspecified Morphology, Sustained                                                                                                                           |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 34           | Ventricular Tachycardia Monomorphic, Sustained                                                                                                                                      |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 35           | Ventricular Tachycardia Polymorphic, Sustained                                                                                                                                      |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 36           | Ventricular Tachycardia Torsade de Pointes, Sustained                                                                                                                               |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 37           | Wandering Atrial Pacemaker                                                                                                                                                          |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 38           | Wolff-Parkinson-White Syndrome                                                                                                                                                      |
+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Heart rate

Can be found for `be`, `be2`, `ie`, and `ie2`.

Feature id is `heart_rate`.

## Durations, voltages

Additional data on mainstream durations and voltages can be found for `be`, `be2` and `ie2` (not for `ie`, don't ask me why).

+----------------------+-------------------------------------------------------------------------+
| var                  | EKG measure                                                             |
+======================+=========================================================================+
| pr_duration          | PR                                                                      |
+----------------------+-------------------------------------------------------------------------+
| qrs_duration         | QRS                                                                     |
+----------------------+-------------------------------------------------------------------------+
| qt_duration          | QT                                                                      |
|                      |                                                                         |
|                      | Also qtcb_duration\_\_c and qtcf_duration\_\_c that are both calculated |
+----------------------+-------------------------------------------------------------------------+
| sokolow_lyon_voltage | QRS voltage (only `be2`, `ie2`)                                         |
+----------------------+-------------------------------------------------------------------------+
| cornell_voltage      | QRS voltage (only `be2`, `ie2`)                                         |
+----------------------+-------------------------------------------------------------------------+
